### ISSUE TITLE
Triage existing chjj/pty.js Issues & PRs

### ISSUE THREAD

**Issue by JamesMGreene** [JamesMGreene/node-partty#1]
### Pull Requests
- [x] chjj/pty.js#27: "extract default rows / cols" &rarr; JamesMGreene/node-partty@ec8869465ead6fbd0350bbf19e7f7635ba0dd52e
- [ ] chjj/pty.js#37: "Report status code of child process in `term.status` property" &rarr; ???
- [ ] chjj/pty.js#72: "Environment vars" &rarr; ???
- [x] chjj/pty.js#82: "Fix Windows build" &rarr; JamesMGreene/node-partty@63774704e1a3b594822f2634b6324426166d35dd
- [ ] chjj/pty.js#84: "Fix issue on kill, process have to consume child output stream or have to waitpid" &rarr; ???
- [x] chjj/pty.js#86: "Fixed install warning" &rarr; JamesMGreene/node-partty@553f3a3007cfc4458f7204ed79a5eb9116bbafe0, JamesMGreene/node-partty@0e6b6d81df94d7e1150f36c386f41ebf361729b6
- [x] chjj/pty.js#87: "Update dependencies" &rarr; JamesMGreene/node-partty@83656149b3b53c77b689a0af6c3810f2f950cd01
- [ ] chjj/pty.js#94: "Switch to new Streams API" &rarr; ???
- [x] ~~chjj/pty.js#102: "just merged this in case someone wants to use it..."~~ &larr; _Unnecessary aggregate PR_
- [ ] chjj/pty.js#110: "Add support for `.on('exit', ...)` returning process exit status" &rarr; ???
- [x] chjj/pty.js#111: "fix windows build errors" &rarr; JamesMGreene/node-partty@8bb1493a060d37b5e370be2cf405a1366cfe485c
- [ ] chjj/pty.js#117: "htop command cannot resize with env.LINES and env.COLUMNS" &rarr; ???
### Issues
- [ ] chjj/pty.js#123: "resource leak when run in multple asynchronous processes" &rarr; ???
- [x] ~~chjj/pty.js#122: "Please release a version of pty.js after update nan to 1.8.4 for iojs build"~~ &larr; _Irrelevant_
- [ ] chjj/pty.js#118: "Input lag?" &rarr; ???
- [ ] chjj/pty.js#98: "Terminal.setEncoding does not work as expected" &rarr; ???
- [ ] chjj/pty.js#97: "Add O_CLOEXEC in all open() calls" &rarr; ???
- [ ] chjj/pty.js#96: "Please use ptsname_r instead of ptsname" &rarr; ???
- [ ] chjj/pty.js#95: "Assertion failed on windows 7 machine" &rarr; ???
- [ ] chjj/pty.js#92: "Error trying to install modules using this on windows 8.1" &rarr; ???
- [ ] chjj/pty.js#90: "Uncaught object in node-webkit" &rarr; ???
- [ ] chjj/pty.js#89: "File is missing '../build/Release/pty.node'" &rarr; ???
- [ ] chjj/pty.js#88: "Any chance to make pty.js compatible with Node 0.11.x?" &rarr; ???
- [x] chjj/pty.js#85: "Missing module in windows..." &rarr; JamesMGreene/node-partty@7b43ebc1fcba746ca55b00c8bb248864225a00be, JamesMGreene/node-partty@cb553ca818d4c0398e2d22a8bed7987ed000a6c2
- [ ] chjj/pty.js#83: "npm install error" &rarr; ???
- [ ] chjj/pty.js#81: "winpty submodule" &rarr; ???
- [x] chjj/pty.js#73: "Ignoring result of chdir() function" &rarr; JamesMGreene/node-partty@553f3a3007cfc4458f7204ed79a5eb9116bbafe0, JamesMGreene/node-partty@0e6b6d81df94d7e1150f36c386f41ebf361729b6
- [ ] chjj/pty.js#69: "Windows Power Shell" &rarr; ???
- [ ] chjj/pty.js#67: "PATH variable is null on windows" &rarr; ???
- [ ] chjj/pty.js#66: "Failed to install pty.js" &rarr; ???
- [ ] chjj/pty.js#65: "Failed to install pty.js" &rarr; ???
- [ ] chjj/pty.js#64: "Spawned process that spawns a subprocess which is not being destroyed" &rarr; ???
- [ ] chjj/pty.js#63: "devtools-terminal npm ERR! pty.js@0.2.3 install" &rarr; ???
- [ ] chjj/pty.js#62: "cannot install on MACOSX with node 0.11.11" &rarr; ???
- [ ] chjj/pty.js#61: "windows: `.kill()` does not work because `.pid` is wrong" &rarr; ???
- [ ] chjj/pty.js#60: "MSBUILD : error MSB4132: The tools version '2.0' is unrecognized. Available tools versions are '4.0'." &rarr; ???
- [ ] chjj/pty.js#59: "How To Scale" &rarr; ???
- [ ] chjj/pty.js#58: "zombie process either by `process.kill` or `pty.destroy`" &rarr; ???
- [ ] chjj/pty.js#56: "cannot install pyt.js" &rarr; ???
- [ ] chjj/pty.js#54: "cannot install on windows" &rarr; ???
- [ ] chjj/pty.js#52: "read out the current working directory" &rarr; ???
- [x] ~~chjj/pty.js#51: "please update npm"~~ &larr; _Irrelevant_
- [ ] chjj/pty.js#48: "issue with cluster module on windows" &rarr; ???
- [ ] chjj/pty.js#45: "include binaries for windows version" &rarr; ???
- [ ] chjj/pty.js#39: "100% CPU usage when pty stays on for long" &rarr; ???
- [ ] chjj/pty.js#34: "on a new system pty is giving `read EIO Use` error and crashing the node process" &rarr; ???
- [ ] chjj/pty.js#33: "Kernel Panic on OSX" &rarr; ???
- [x] ~~chjj/pty.js#31: "pty.js and npm"~~ &larr; _Irrelevant_
- [ ] chjj/pty.js#28: "exit code" &rarr; ???
- [ ] chjj/pty.js#18: "Disable stdin echo" &rarr; ???
